### ISSUE TITLE
include "nnue.h" error

### ISSUE THREAD

**Issue by maksimKorzh** [dshawul/nnue-probe#1]
Hi Daniel, first of all THANK YOU SO MUCH for creating this lib.
Most likely the issue in my poor skills and misunderstanding rather than in a lib itself.
Anyway, here's the issue I'm facing:

After compiling library and getting libnnueprobe.so file I'm doing next steps:

1. Created test.c file with following content
```
#include "nnue.h"

int main()
{
    nnue_init("nn-04cf2b4ed1da.nnue");
    return 0;
}
```

2. Compiling with command
gcc -L/home/maksim/Desktop/nnue-probe/src test.c -o test

3. Getting this error:
```
In file included from nnue.h:4:0,
                 from test.c:1:
misc.h:52:41: error: expected ‘;’, ‘,’ or ‘)’ before ‘&’ token
 void decode_fen(const char* fen_str, int& player, int& castle,
                                         ^
In file included from test.c:1:0:
nnue.h:44:3: error: expected specifier-qualifier-list before ‘alignas’
   alignas(64) int16_t accumulation[2][256];
   ^~~~~~~
nnue.h:59:19: error: unknown type name ‘Position’
 int nnue_evaluate(Position* pos);
                   ^~~~~~~~
nnue.h:15:29: error: expected identifier or ‘(’ before string constant
 #   define DLLExport extern "C"
                             ^
nnue.h:64:1: note: in expansion of macro ‘DLLExport’
 DLLExport void _CDECL nnue_init(
 ^~~~~~~~~
nnue.h:15:29: error: expected identifier or ‘(’ before string constant
 #   define DLLExport extern "C"
                             ^
nnue.h:71:1: note: in expansion of macro ‘DLLExport’
 DLLExport int _CDECL nnue_evaluate_fen(
 ^~~~~~~~~
nnue.h:15:29: error: expected identifier or ‘(’ before string constant
 #   define DLLExport extern "C"
                             ^
nnue.h:91:1: note: in expansion of macro ‘DLLExport’
 DLLExport int _CDECL nnue_evaluate(
 ^~~~~~~~~
test.c: In function ‘main’:
test.c:6:5: warning: implicit declaration of function ‘nnue_init’ [-Wimplicit-function-declaration]
     nnue_init("nn-04cf2b4ed1da.nnue");
```

Humbly asking what am I doing wrong, please help

**Comment by maksimKorzh** [comment]
Ok, the above was fixed by using g++ instead of gcc, but I'm still having undefined reference to `nnue_init' error, probably need to make it extern or something

**Comment by maksimKorzh** [comment]
Solved this issue by using g++ instead of gcc

**Comment by dshawul** [comment]
Thanks.
I have made it to work with gcc now.

**Comment by maksimKorzh** [comment]
Thank you so much, Daniel! Now it works like a charm!
I've been also testing it with python, there are also some issues - 
1. Your snippet seems to be Python2 which is now deprecated, any way it didn't work for me - after loading NNUE via
nnue.nnue_init("nn-04cf2b4ed1da.nnue")
I'm getting this output
Loading NNUE : nn-04cf2b4ed1da.nnue
Illegal instruction (core dumped)
2. If try it on python3 after
nnue.nnue_init("nn-04cf2b4ed1da.nnue")
I'm getting this output
Loading NNUE : n   // literally takes only first character of the string
NNUE file not found!

**Comment by dshawul** [comment]
I have fixed the python example bug now. 
The strings passed from python for both the nnue file and the FEN string need to be 
prefixed by "b" to indicate it is a C type string.

**Comment by maksimKorzh** [comment]
Thanks Daniel, thank you so much!
Sorry for annoying but I've found couple more issues:
1. It doesn't cross compile with gcc for windows, while does with g++
2. I'm not sure it's a an issue, but when I was making youtube tutorials I've noticed following problem:
Let's take this position:
r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3
[stockfish evaluation guide](https://hxim.github.io/Stockfish-Evaluation-Guide/) gives score of 35
while lib with both FEN or direct probing gives -35
This happens for some other positions a well.
Values are always the same but the sign is not.
I'm not sure is this is ok.
May be it's the matter of Ronald De Man's code, not yours.
Maybe it's a bug on stockfish evaluation guide. If so - we need to tell them.

**Comment by maksimKorzh** [comment]
And btw can it get compiled on windows with gcc? I don't have windows, hence can't test, but my viewers mostly use windows...

**Comment by dshawul** [comment]
The library returns a score relative to the side to move. This is convenient for use in an engine.
I have added some description regarding that now.

It should compile fine under windows woth MSVC but one has to set the proper flags following the Makefile.
I am able to cross-compile for windows from linus using mingw compiler
```
$ make clean; make COMP=win
rm -rf misc.o nnue.o libnnueprobe.so core.* cluster.* *.gcda
make libnnueprobe.so strip
make[1]: Entering directory '/home/daniel/egbbSource/nnue-probe/src'
x86_64-w64-mingw32-g++ -Wall -fstrict-aliasing -fno-exceptions -fno-rtti  -Wno-unused-variable -Wno-unused-result -Wno-unused-but-set-variable -Wno-maybe-uninitialized -std=c++11 -Ofast -fomit-frame-pointer  -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_SSE -msse -c -fPIC -o misc.o misc.cpp
x86_64-w64-mingw32-g++ -Wall -fstrict-aliasing -fno-exceptions -fno-rtti  -Wno-unused-variable -Wno-unused-result -Wno-unused-but-set-variable -Wno-maybe-uninitialized -std=c++11 -Ofast -fomit-frame-pointer  -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_SSE -msse -c -fPIC -o nnue.o nnue.cpp
x86_64-w64-mingw32-g++ -o libnnueprobe.so misc.o nnue.o -lm -static -shared 
x86_64-w64-mingw32-strip libnnueprobe.so
make[1]: Leaving directory '/home/daniel/egbbSource/nnue-probe/src'
```

**Comment by maksimKorzh** [comment]
Ok, thanks.
re: The library returns a score relative to the side to move.
hmm.. this is strange because if I don't assign sign depending on side it starts giving pieces away... probably I'm doing something wrong.

Anyway.

I had a look at your Scorpio code (from talkchess link), sorry, it's too complicated for me.
Can you please tel me whether this formula is ok to calculate final score:

```
score = material_score();

// get NNUE positional score
int nnue_score = evaluate_nnue(side, pieces, squares) * 5 / 4;
    
// assign score based on side to move
(side == white) ? nnue_score : (nnue_score = -nnue_score);

final_score = material_score + nnue_score
```

Is this correct?
 evaluate_nnue(side, pieces, squares) * 5 / 4; // * 5 / 4 I took from Cfish

Can you please provide your formula?
My material is using tapered eval, but for simplicity could you please give a formula to aggregate nnue and material score?

P.S. without using material score it sacs queen in every game

**Comment by dshawul** [comment]
That code is wrong. First you don't have to negate the score. Second mixing the material_score with the nnue_score is not needed because the nnue_score already has the material score in it. Scaling will only be necessary if you want to do a hybrid nnue + classical score. I don't do that in my engine and use pure NNUE score without scaling 
```
final_score =  nnue_evaluate(side, pieces, score)
```

**Comment by maksimKorzh** [comment]
Thanks, for clarification!

**Comment by maksimKorzh** [comment]
Hold on a sec, is it a typo? may be:
final_score =  nnue_evaluate(side, pieces, squares)  // squares instead of score

I have no idea what am I doing wrong but returning final score like that leads to game like this:

[Event "Computer chess game"]
[Site "maksim-Inspiron-3582"]
[Date "2020.10.17"]
[Round "?"]
[White "BBC NNUE [youtube]"]
[Black "BBC NNUE [youtube]"]
[Result "1-0"]
[BlackElo "2200"]
[ECO "A21"]
[Opening "English"]
[Time "20:33:45"]
[WhiteElo "2200"]
[TimeControl "30+0"]
[Termination "normal"]
[PlyCount "33"]
[WhiteType "program"]
[BlackType "program"]

1. c4 {(c2-c4 e7-e5 Nb1-c3 Nb8-c6 Ng1-f3 d7-d5) -0.00/6 1} e5 {(e7-e5
Qd1-a4 Qd8-h4 d2-d3 Bf8-c5) +0.53/5 1} 2. Nc3 {(Nb1-c3 c7-c6 Ng1-f3 d7-d5)
-0.36/4 0} Bb4 {(Bf8-b4 Ng1-f3 c7-c6 Qd1-c2 d7-d5) -0.00/5 1} 3. e3 {(e2-e3
Bb4-a5 Ke1-e2 Qd8-g5 Ng1-f3) -0.00/5 0} b5 {(b7-b5 Ke1-e2 Qd8-h4 c4-c5)
+0.31/4 0} 4. e4 {(e3-e4 Ke8-e7 Ke1-e2) -0.00/3 0} Ke7 {(Ke8-e7 Ke1-e2
Ke7-d6 Ke2-d3) -0.00/4 0} 5. cxb5 {(c4xb5 d7-d5 Nc3-a4 d5xe4) +0.04/4 0} d5
{(d7-d5 Nc3-a4 d5xe4) -0.04/3 0} 6. Nxd5+ {(Nc3xd5+ Ke7-e8 Nd5xb4 Bc8-b7)
+11.02/3 0} Kd6 {(Ke7-d6 Ke1-e2 Bb4xd2 Ke2-d3) +5.24/3 0} 7. Nf6 {(Nd5-f6
g7xf6 f2-f4 Bc8-f5 Qd1-h5) -0.00/5 0} gxf6 {(g7xf6 Bf1-c4 Kd6-e7) +3.90/3
0} 8. Qb3 {(Qd1-b3 Qd8-d7 Qb3-d5+ Kd6-e7 Qd5xa8 Qd7xb5) +1.11/5 0} Be6
{(Bc8-e6 Qb3-d5+ Kd6-e7 Qd5-b7) +2.37/3 0} 9. Qxb4+ {(Qb3xb4+ c7-c5 Qb4-c3
f6-f5 e4xf5 Nb8-d7) +6.30/5 0} Kd7 {(Kd6-d7 Ke1-e2 Qd8-f8 Qb4-a5) +5.13/3
0} 10. Ke2 {(Ke1-e2 Qd8-f8 Qb4-c3 Kd7-d6 Ke2-d3) -0.00/5 0} Bc4+ {(Be6-c4+
Ke2-e3 Qd8-e8 Ng1-h3) +3.82/3 0} 11. Qxc4 {(Qb4xc4 Kd7-e8 Qc4xf7+ Ke8xf7
Ke2-e1 Qd8-d3 Ng1-f3) -0.00/5 0} Ke8 {(Kd7-e8 Qc4xf7+ Ke8xf7 Ke2-e1 Qd8-d3
Ng1-f3) +5.35/5 0} 12. Ke3 {(Ke2-e3 Ng8-h6 Qc4-e2 Ke8-d7 Ke3-d3) -0.00/5 0}
Qxd2+ {(Qd8xd2+ Ke3-f3 Qd2-b4 Qc4-e2 Ke8-d7 Kf3-e3) +8.11/5 0} 13. Bxd2
{(Bc1xd2 Ng8-e7 f2-f4 e5xf4+ Ke3-d4 f4-f3 Qc4-b4) -0.00/5 0} Ne7 {(Ng8-e7
f2-f4 e5xf4+ Ke3-d4 f4-f3 Qc4-b4) +1.43/5 0} 14. Qxc7 {(Qc4xc7 Rh8-g8
Qc7xb8+ Ra8xb8 Ke3-f3 Ke8-d7) -0.00/5 0} Nd5+ {(Ne7-d5+ Ke3-d3 Nd5xc7
Kd3-c4 Nb8-d7 Bd2-c1) +4.18/5 0} 15. exd5 {(e4xd5 e5-e4 Qc7-a5 Nb8-d7)
+31.72/3 0} e4 {(e5-e4 Qc7-a5 Rh8-g8 d5-d6 Rg8xg2) -0.00/5 0} 16. Qc8+
{(Qc7-c8+ Ke8-e7 Bd2-b4+) +M2/6 0} Ke7 {(Ke8-e7 Bd2-b4+) -M2/6 0} 17. Bb4#
{(Bd2-b4+) +M1/6 0} 1-0

weird(((

**Comment by maksimKorzh** [comment]
Daniel, I'm so so sorry, the issue is that I'm a complete idiot - had typos in my code.
Now all works like a charm, thank you so so much!

**Comment by maksimKorzh** [comment]
Hi Daniel, please don't hate me, one last thing (I hope)

I'm trying to cross compile my engine with NNUE support (now everything works like a charm thanks to you!)
It compiles well with gcc but with cross compiler I'm getting this weird error:

```
gcc -Ofast bbc.c nnue_eval.c ./nnue/nnue.cpp ./nnue/misc.cpp -o bbc
x86_64-w64-mingw32-gcc -Ofast bbc.c nnue_eval.c ./nnue/nnue.cpp ./nnue/misc.cpp -lws2_32 -o bbc.exe
/tmp/ccTdrw9g.o:nnue_eval.c:(.text+0x3): undefined reference to `__imp_nnue_init'
/tmp/ccTdrw9g.o:nnue_eval.c:(.text+0x13): undefined reference to `__imp_nnue_evaluate'
/tmp/ccTdrw9g.o:nnue_eval.c:(.text+0x23): undefined reference to `__imp_nnue_evaluate_fen'
collect2: error: ld returned 1 exit status
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

```

File nnue_eval.c is created by me. It uses wrappers for nnue-probe lib functions. I can't include "nnue.h" directly because of variable name collissions

here's my nnue_eval.c

```
/* NNUE wrapping functions */

// include headers
#include "./nnue/nnue.h"
#include "nnue_eval.h"

// init NNUE
void init_nnue(char *filename)
{
    // call NNUE probe lib function
    nnue_init(filename);
}

// get NNUE score directly
int evaluate_nnue(int player, int *pieces, int *squares)
{
    // call NNUE probe lib function
    nnue_evaluate(player, pieces, squares);
}

// det NNUE score from FEN input
int evaluate_fen_nnue(char *fen)
{
    // call NNUE probe lib function
    nnue_evaluate_fen(fen);
}
```

I know it's not an issue with your brilliant lib, but I stuck and can't provide my users a windows version, please help.

**Comment by dshawul** [comment]
It can now compile with microsoft's MSVC compiler. I have actually built a binary with it on windows machine.
The binary is available here.
https://github.com/dshawul/Scorpio/releases/download/3.0/nnprobe-windows-cpu.zip
The package also contains another library for probin Lc0 nets and my own deep nets as well.

**Comment by maksimKorzh** [comment]
Awesome! Thanks!
