### ISSUE TITLE
undefined symbol errors

### ISSUE THREAD

**Issue by linux-leo** [dshawul/nnue-probe#3]
I was looking forward to trying out nnue myself, but after copying the example code i always get undefined symbol errors.

`import os`
`from ctypes import *`
`nnue = cdll.LoadLibrary(os.path.abspath("libnnprobe.so"))`
`nnue.nnue_init(b"nn-04cf2b4ed1da.nnue")`
`score = nnue.nnue_evaluate_fen(b"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1")`
`print("Score = ", score)`

`Traceback (most recent call last):
  File "main.py", line 5, in <module>
    nnue.nnue_init(b"nn-04cf2b4ed1da.nnue")
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/runner/chess-engine/libnnprobe.so: undefined symbol: nnue_init`

**Comment by dshawul** [comment]
You are not loading the right so file. It is `libnnueprobe.so` not `libnnprobe.so`

```
from __future__ import print_function
from ctypes import *
nnue = cdll.LoadLibrary("libnnueprobe.so")
nnue.nnue_init(b"nn-04cf2b4ed1da.nnue")
score = nnue.nnue_evaluate_fen(b"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1")
print("Score = ", score)
```

**Comment by linux-leo** [comment]
I am using the files from the scorpio 3 chess engine, because i thought they were based on this project. (nnprobe-ubuntu-cpu.zip)
So i should have compiled this repo instead, right?
